services:
  # Contenedor de Base de Datos
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: asistencia_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432" # Opcional: solo si quieres conectarte desde DBeaver en tu PC
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-admin} -d asistencia_db"]
      interval: 3s
      timeout: 5s
      retries: 5

  # Contenedor de tu Web + Scraper
  web:
    build: ./web
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASS}@db:5432/asistencia_db
      - SECRET_KEY=${SECRET_KEY}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_NAME=${ADMIN_NAME}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./web:/app  # Para que si cambias código, se actualice sin reconstruir

volumes:
  postgres_data:

